Repository obsproject/obs-websocket, pull requests merged in 2020-03, with the labels that each got.

#416 Fix SetStreamSettings when switching type
  src/WSRequestHandler_Streaming.cpp
Labels: bug

#324 Show alignment (gravity) of scene elements when querying/switching scenes
  docs/generated/comments.json
  docs/generated/protocol.md
  src/Utils.cpp
  src/WSRequestHandler_SceneItems.cpp
Labels: reviewable

#321 Fire an event whenever an item is locked/unlocked
  src/WSEvents.cpp
  src/WSEvents.h
Labels: feature, reviewable

#338 Create a command for opening a projector.
  docs/generated/comments.json
  docs/generated/protocol.md
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_General.cpp
Labels: feature, reviewable

#428 Add a 'muted' flag to GetSceneItems
  docs/generated/comments.json
  docs/generated/protocol.md
  src/Utils.cpp
  src/WSRequestHandler_SceneItems.cpp
Labels: feature

#429 requests(SetSyncOffset): allow negative offsets
  azure-pipelines.yml
  src/WSRequestHandler_Sources.cpp
Labels: bug

#431 request(GetVersion): add supported image export formats list
  src/WSRequestHandler_General.cpp
Labels: feature

#410 feat(events): add "TransitionEnd" and "TransitionVideoEnd" events
  src/Utils.cpp
  src/Utils.h
  src/WSEvents.cpp
  src/WSEvents.h
Labels: feature

#438 Remove dynloaded functions
  CI/install-dependencies-xenial.sh
  src/Utils.cpp
  src/Utils.h
  src/WSEvents.cpp
  src/WSRequestHandler_General.cpp
  src/WSRequestHandler_Recording.cpp
  src/WSRequestHandler_Streaming.cpp
Labels: refactoring

#434 Fix crash when calling EnableStudioMode/DisableStudioMode/ToggleStudioMode
  src/WSRequestHandler_StudioMode.cpp
Labels: bug

#422 Migrate Windows & Linux builds to Azure Pipelines
  .gitignore
  .travis.yml
  CI/build-ubuntu.sh
  CI/checkout-cmake-obs-windows.cmd
  CI/download-obs-deps.cmd
  CI/generate-docs.sh
  CI/install-dependencies-ubuntu.sh
  CI/install-dependencies-xenial.sh
  CI/install-qt-win.cmd
  CI/install-setup-qt.cmd
  CI/package-macos.sh
  CI/package-ubuntu.sh
  CI/package-windows.cmd
  CI/package-xenial.sh
  CI/prepare-windows.cmd
  CMakeLists.txt
  appveyor.yml
  azure-pipelines.yml
Labels: enhancement

#420 Fix crash when sending an event on exit
  CMakeLists.txt
  src/WSEvents.cpp
  src/protocol/OBSRemoteProtocol.cpp
  src/rpc/RpcEvent.cpp
  src/rpc/RpcEvent.h
Labels: bug

#448 Allow Get/Set text gdiplus/ft2 properties functions to operate on v2 sources
  src/WSRequestHandler_Sources.cpp
Labels: bug

#449 Target Scene Items per ID, in addition to scene name and source name
  src/Utils.cpp
  src/Utils.h
  src/WSEvents.cpp
  src/WSRequestHandler_SceneItems.cpp
Labels: bug
