Repository obsproject/obs-websocket, pull requests merged in 2020-04, with the labels that each got.

#453 ci(macos): fix install_name_tool packaging step
  CI/package-macos.sh
Labels: bug

#461 cmake(msvc): disable FH4
  CMakeLists.txt
Labels: bug, packaging

#464 ci(macos): add automated codesigning + notarization
  CI/macos/obs-websocket.pkgproj
  CI/package-macos.sh
  azure-pipelines.yml
Labels: feature

#478 Ubuntu packaging fixes
  CI/package-ubuntu.sh
  CMakeLists.txt
Labels: bug

#482 Add websocketpp error message to error dialog box
  data/locale/en-US.ini
  src/WSServer.cpp
Labels: feature

#474 Suppress websocketpp logging entries
  src/WSServer.cpp
Labels: patch
