Repository obsproject/obs-websocket, pull requests merged in 2020-09, with the labels that each got.

#573 Docs: Add `enabled` field to `SourceFiltersReordered`
  src/WSEvents.cpp
Labels: patch

#578 Docs: Fix requests marked as "unreleased"
  src/WSRequestHandler_Scenes.cpp
Labels: patch

#583 Installer: Don't show warning when obs directory is not empty
  installer/installer.iss
Labels: patch

#559 Settings: Add option to lock binding to IPv4
  data/locale/en-US.ini
  src/Config.cpp
  src/Config.h
  src/WSServer.cpp
  src/WSServer.h
  src/forms/settings-dialog.cpp
  src/forms/settings-dialog.ui
  src/obs-websocket.cpp
Labels: enhancement

#560 Requests: Scene collection and profile name checking
  src/Utils.cpp
  src/Utils.h
  src/WSRequestHandler_Profiles.cpp
  src/WSRequestHandler_SceneCollections.cpp
Labels: enhancement

#597 Fix macOS CI
  CI/install-dependencies-macos.sh
  CI/macos/qt.rb
Labels: bug
