Repository obsproject/obs-websocket, pull requests merged in 2020-07, with the labels that each got.

#529 Requests: Fix useDecibel response when volume is -infinity
  src/WSRequestHandler_Sources.cpp
Labels: patch

#505 Docs: Update and split up main documentation
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE.md
  .github/images/obsws_logo.png
  .github/pull_request_template.md
  BUILDING.md
  CONTRIBUTING.md
  README.md
Labels: discussion, enhancement

#547 Requests, Events: Add support for Audio Active
  src/WSEvents.cpp
  src/WSEvents.h
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Sources.cpp
Labels: feature

#549 Requests: Add Replay Buffer and Recording Statuses
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Recording.cpp
  src/WSRequestHandler_ReplayBuffer.cpp
Labels: feature

#550 Docs: Move ssl tunnelling guide to its own page
  README.md
  SSL-TUNNELLING.md
Labels: enhancement

#497 Requests/Events: Media Source/VLC
  CMakeLists.txt
  src/WSEvents.cpp
  src/WSEvents.h
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_MediaControl.cpp
Labels: feature

#551 Requests/Events: Use sourceKind instead of sourceTypeId
  src/WSEvents.cpp
  src/WSRequestHandler_MediaControl.cpp
Labels: patch

#527 Requests: Sceneitem manipulation requests
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_SceneItems.cpp
Labels: feature

#557 TakeSourceScreenshot: default to current scene
  src/WSRequestHandler_Sources.cpp
Labels: enhancement, nonbreaking change

#571 Utils(GetTrayIcon): refactor with frontend API function
  src/Utils.cpp
Labels: bug
