Repository obsproject/obs-websocket, pull requests merged in 2020-11, with the labels that each got.

#605 Get/Set Transition Settings
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Sources.cpp
  src/WSRequestHandler_Transitions.cpp
Labels: feature

#618 requests(outputs): fix corrupted parameters object on MSVC when using findOutputOrFail
  src/WSRequestHandler_Outputs.cpp
Labels: bug

#439 T-Bar control
  CI/install-dependencies-ubuntu.sh
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_StudioMode.cpp
  src/WSRequestHandler_Transitions.cpp
Labels: feature

#619 Events: provide new state of entity (in events that don't do it already)
  src/WSEvents.cpp
Labels: enhancement

#589 Requests: Add CreateSource and clean up code
  src/Utils.cpp
  src/Utils.h
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_SceneItems.cpp
  src/WSRequestHandler_Sources.cpp
Labels: feature

#621 Feature/current recording filename
  src/Utils.cpp
  src/Utils.h
  src/WSEvents.cpp
  src/WSRequestHandler_Recording.cpp
Labels: feature
