Repository obsproject/obs-websocket, pull requests merged in 2020-05, with the labels that each got.

#483 Add obs-websocket-http
  README.md
Labels: enhancement

#491 Deprecate SetBrowserSourceProperties and GetBrowserSourceProperties
  src/WSRequestHandler_Sources.cpp
Labels: patch

#493 Add error system to EnableStudioMode and DisableStudioMode
  src/WSRequestHandler_StudioMode.cpp
Labels: enhancement, nonbreaking change

#481 Fix install dir on Ubuntu by using new cmake flag
  BUILDING.md
  CI/build-ubuntu.sh
  CMakeLists.txt
Labels: patch

#504 ci(windows): simplified OBS Preparation script + shorter build times
  CI/checkout-cmake-obs-windows.cmd
  CI/prepare-obs-windows.cmd
  azure-pipelines.yml
Labels: ci

#503 Requests: Add GetTransitionPosition
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Transitions.cpp
Labels: feature, nonbreaking change

#495 Requests: Add useDecibel bool to GetVolume and SetVolume
  src/WSRequestHandler_Sources.cpp
Labels: enhancement, nonbreaking change

#484 Requests: Add new parameters to TakeSourceScreenshot
  src/WSRequestHandler_Sources.cpp
Labels: breaking change, enhancement

#496 Requests: Add audio monitoring requests
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Sources.cpp
Labels: feature, nonbreaking change

#510 General: Fix a few warnings
  src/WSEvents.cpp
  src/WSRequestHandler_Scenes.cpp
  src/WSRequestHandler_Sources.cpp
  src/WSRequestHandler_Streaming.cpp
Labels: patch

#508 Requests: Add SetSourceName (renaming sources)
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Sources.cpp
Labels: feature

#516 Requests: Add scene transition override requests
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Scenes.cpp
Labels: feature
