Repository obsproject/obs-websocket, pull requests merged in 2021-02, with the labels that each got.

#666 Requests: Add RefreshBrowserSource
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_Sources.cpp
Labels: feature

#665 Batch Requests
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_General.cpp
  src/WSServer.cpp
  src/protocol/OBSRemoteProtocol.cpp
  src/protocol/OBSRemoteProtocol.h
  src/rpc/RpcResponse.h
Labels: feature

#668 Cleanup for v4.9.0
  CI/macos/obs-websocket.pkgproj
  CMakeLists.txt
  docs/partials/introduction.md
  installer/installer.iss
  src/WSEvents.cpp
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_General.cpp
  src/WSRequestHandler_MediaControl.cpp
  src/WSRequestHandler_Recording.cpp
  src/WSRequestHandler_ReplayBuffer.cpp
  src/WSRequestHandler_SceneItems.cpp
  src/WSRequestHandler_Scenes.cpp
  src/WSRequestHandler_Sources.cpp
  src/WSRequestHandler_Streaming.cpp
  src/WSRequestHandler_Transitions.cpp
  src/obs-websocket.h
Labels: enhancement

#674 CI: Fix tag detection
  CI/package-ubuntu.sh
Labels: bug, ci

#687 Requests: Add Sleep
  src/WSRequestHandler.cpp
  src/WSRequestHandler.h
  src/WSRequestHandler_General.cpp
Labels: feature
