Repository obsproject/obs-websocket, pull requests merged in 2021-06, with the labels that each got.

#758 CI: Fix some various stuff getting in the way of doing 4.9.1 dev
  .github/workflows/pr_push.yml
  .github/workflows/tag_release.yml
  CI/linux/install-dependencies-ubuntu.sh
  CI/windows/prepare-obs-windows.cmd
  azure-pipelines.yml
Labels: bug, ci, enhancement

#760 Fix small pipeline typo
  azure-pipelines.yml
Labels: bug, ci

#692 Events: Fix multiple shutdown crashes
  src/WSEvents.cpp
  src/WSServer.cpp
  src/WSServer.h
Labels: bug
